name: auto-generate-gitbook
on:
  push:
    branches:
      - main

steps:
  - name: checkout main
    uses: actions/checkout@v2
    with:
      ref: main

  - name: install nodejs
    uses: actions/setup-node@v1

  - name: configue gitbook
    run: |
      npm install -g gitbook-cli
      gitbook install

  - name: generate _book folder
    run: |
      gitbook build

  - name: push _book to branch gh-pages
    env:
      TOKEN: ${{ secrets.TOKEN }}
      REF: github.com/${{github.repository}}
      MYEMAIL: 466565029@qq.com # ！！记得修改为自己github设置的邮箱
      MYNAME: ${{github.repository_owner}}
    run: |
      cd _book
      git config --global user.email "${MYEMAIL}"
      git config --global user.name "${MYNAME}"
      git init
      git remote add origin https://${REF}
      git add . 
      git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
      git branch -M main
      git push --force --quiet "https://${TOKEN}@${REF}" main:gh-pages

 - name: build and push docker image to docker.io
   run: |
      echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      docker build -t swxs/booook .
      docker push swxs/booook
